package net.eightdigger.bug_friends.entity.animations;

import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;

public class ModAnimationDefinitons {
    public static final AnimationDefinition BEETLE_WALK = AnimationDefinition.Builder.withLength(1.32f)
        .addAnimation("head",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                        new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.16f, KeyframeAnimations.degreeVec(-3.5f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.48f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.8f, KeyframeAnimations.degreeVec(-3.5f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1.12f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1.28f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("fR",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                        new Keyframe(0f, KeyframeAnimations.degreeVec(0f, -7.5f, 0f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.16f, KeyframeAnimations.degreeVec(-5.38f, -19.29f, 15.92f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.32f, KeyframeAnimations.degreeVec(-12.29f, -30.32f, 23.34f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.48f, KeyframeAnimations.degreeVec(-22.35f, -30.1f, 40.73f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.64f, KeyframeAnimations.degreeVec(0f, -42.5f, 0f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.8f, KeyframeAnimations.degreeVec(0f, -32.5f, 0f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.96f, KeyframeAnimations.degreeVec(0f, -20f, 0f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1.28f, KeyframeAnimations.degreeVec(0f, -7.5f, 0f),
                                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("mR",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                        new Keyframe(0f, KeyframeAnimations.degreeVec(1.3f, 4.83f, 15.05f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.16f, KeyframeAnimations.degreeVec(0f, 0f, 25f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.32f, KeyframeAnimations.degreeVec(0f, -5f, 0f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.48f, KeyframeAnimations.degreeVec(0f, 7.5f, 0f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.64f, KeyframeAnimations.degreeVec(0f, 12.5f, 0f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.8f, KeyframeAnimations.degreeVec(0f, 20f, 0f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.96f, KeyframeAnimations.degreeVec(0f, 37.5f, 0f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1.12f, KeyframeAnimations.degreeVec(0f, 32.5f, 0f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1.28f, KeyframeAnimations.degreeVec(1.3f, 4.83f, 15.05f),
                                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("bR",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                        new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 20f, 0f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.16f, KeyframeAnimations.degreeVec(0f, 27.5f, 0f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.32f, KeyframeAnimations.degreeVec(0f, 45f, 0f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.48f, KeyframeAnimations.degreeVec(0f, 55f, 0f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.64f, KeyframeAnimations.degreeVec(0f, 62.5f, 0f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.8f, KeyframeAnimations.degreeVec(19.72f, 46.94f, 26.13f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.96f, KeyframeAnimations.degreeVec(8.29f, 39.27f, 12.96f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1.12f, KeyframeAnimations.degreeVec(0f, 40f, 0f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1.28f, KeyframeAnimations.degreeVec(0f, 20f, 0f),
                                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("fL",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                        new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 37.5f, 0f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.32f, KeyframeAnimations.degreeVec(0f, 27.5f, 0f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.48f, KeyframeAnimations.degreeVec(0f, 2.5f, 0f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.64f, KeyframeAnimations.degreeVec(0f, -10f, 0f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.8f, KeyframeAnimations.degreeVec(-1.95f, 7.24f, -15.12f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.96f, KeyframeAnimations.degreeVec(-7.1f, 18.75f, -21.17f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1.12f, KeyframeAnimations.degreeVec(0f, 30f, 0f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1.28f, KeyframeAnimations.degreeVec(0f, 37.5f, 0f),
                                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("mL",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                        new Keyframe(0f, KeyframeAnimations.degreeVec(0f, -5f, 0f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.16f, KeyframeAnimations.degreeVec(0f, -25f, 0f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.32f, KeyframeAnimations.degreeVec(0f, -42.5f, 0f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.48f, KeyframeAnimations.degreeVec(2.5f, -44.95f, -3.53f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.64f, KeyframeAnimations.degreeVec(0f, -20f, 0f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.8f, KeyframeAnimations.degreeVec(-0.33f, 2.48f, -7.51f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.96f, KeyframeAnimations.degreeVec(-9.95f, 8.36f, -18.96f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1.12f, KeyframeAnimations.degreeVec(-6.5f, 11.25f, 1.13f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1.28f, KeyframeAnimations.degreeVec(0f, -5f, 0f),
                                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("bL",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                        new Keyframe(0f, KeyframeAnimations.degreeVec(0f, -50f, 0f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.16f, KeyframeAnimations.degreeVec(13.67f, -46.83f, -18.44f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.32f, KeyframeAnimations.degreeVec(16.63f, -43.87f, -23.06f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.48f, KeyframeAnimations.degreeVec(14.51f, -43.08f, -20.75f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.64f, KeyframeAnimations.degreeVec(0f, -32.5f, 0f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.8f, KeyframeAnimations.degreeVec(0f, -42.5f, 0f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1.12f, KeyframeAnimations.degreeVec(0f, -57.5f, 0f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1.28f, KeyframeAnimations.degreeVec(0f, -50f, 0f),
                                AnimationChannel.Interpolations.LINEAR))).build();
    public static final AnimationDefinition BEETLE_ATTACK = AnimationDefinition.Builder.withLength(1.04f)
            .addAnimation("head",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.2f, KeyframeAnimations.posVec(0f, 0f, 1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.44f, KeyframeAnimations.posVec(0f, 0f, -0.5f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.76f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("head",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.36f, KeyframeAnimations.degreeVec(15f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.48f, KeyframeAnimations.degreeVec(-27.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.76f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("body",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.2f, KeyframeAnimations.posVec(0f, 0f, 1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.44f, KeyframeAnimations.posVec(0f, 0f, -0.5f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.76f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("fR",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.2f, KeyframeAnimations.degreeVec(0f, -22.5f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.44f, KeyframeAnimations.degreeVec(0f, 17.5f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.76f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("mR",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.2f, KeyframeAnimations.degreeVec(0f, -22.5f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.44f, KeyframeAnimations.degreeVec(0f, 17.5f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.76f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("bR",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.2f, KeyframeAnimations.degreeVec(0f, -22.5f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.44f, KeyframeAnimations.degreeVec(0f, 17.5f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.76f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("fL",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.2f, KeyframeAnimations.degreeVec(0f, 22.5f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.44f, KeyframeAnimations.degreeVec(0f, -17.5f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.76f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("mL",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.2f, KeyframeAnimations.degreeVec(0f, 22.5f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.44f, KeyframeAnimations.degreeVec(0f, -17.5f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.76f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("bL",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.2f, KeyframeAnimations.degreeVec(0f, 22.5f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.44f, KeyframeAnimations.degreeVec(0f, -17.5f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.76f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR))).build();
    public static final AnimationDefinition POSE = AnimationDefinition.Builder.withLength(0.04f)
            .addAnimation("head",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-9.85f, -1.73f, -9.85f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("fR",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, -22.5f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("bR",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 22.5f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("fL",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-6.12f, 21.69f, -16.17f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("bL",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, -22.5f, 0f),
                                    AnimationChannel.Interpolations.LINEAR))).build();
    public static final AnimationDefinition BEETLE_IDLE = AnimationDefinition.Builder.withLength(0.04f).build();
    public static final AnimationDefinition BEETLE_SIT = AnimationDefinition.Builder.withLength(0f)
            .addAnimation("head",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-17.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR))).build();
}
